---
- hosts: web
  become: yes

  tasks:

    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy docker compose file
      copy:
        src: ../../docker-compose.yml
        dest: /home/ec2-user/docker-compose.yml

    - name: Pull images
      command: docker compose pull
      args:
        chdir: /home/ec2-user

    - name: Start services
      command: docker compose up -d
      args:
        chdir: /home/ec2-user